### ISSUE TITLE
Keep getting AccessDenied: Missing credentials in config

### ISSUE THREAD

**Issue by samiajia** [Peksa/pek.so#1]
Hi, first of all I would like to say thanks! This is a great work!
Below is my config:
...

Can you please let me know what's wrong? Thank you very much :)

**Comment by Peksa** [comment]
Hi there!

I'm not quite sure what causes the error. Your IAM policies look correct when comparing to mine. I noted that we use different AWS regions and I found this that might be relevant: http://stackoverflow.com/questions/27499629/when-using-cognito-credentials-with-aws-in-a-browser-javascript-keep-getting

I've updated the code to set the region before setting the credentials and I also updated aws-sdk-js to the latest version.

Could you please check if either of these updates solves your problem? The updates are in app.js and index.html so you'll have to re-upload these to S3 (remember to keep your modifications). 

Thanks for trying it out! :)

**Comment by samiajia** [comment]
Hi thank you very much for your updates, however it didnt solve the problem. It gave me the same error:

![screen shot 2015-05-22 at 9 14 48 pm](https://cloud.githubusercontent.com/assets/4963141/7772364/dc97d3e0-00c7-11e5-9fd6-5c04d043ee55.png)

Maybe my region code is not right. Pls see below for my setting:
![screen shot 2015-05-22 at 9 18 26 pm](https://cloud.githubusercontent.com/assets/4963141/7772406/318a1034-00c8-11e5-9bce-d3246b32ed2c.png)

Maybe ap-southeast-1 is not the right code for Singapore region?

**Comment by Peksa** [comment]
From the error message, it looks like amazon doesn't think you are authorized to assume the role you've set up. Have you double checked your IAM Policy Document (under Trust Relationships)? The Facebook app id and your profile id are correct? I noted that you're missing a closing `}` , but that might just be from pasting here.

Here's mine for reference:

``` js
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Federated": "graph.facebook.com"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "graph.facebook.com:app_id": "602729056487961",
          "graph.facebook.com:id": "717273996"
        }
      }
    }
  ]
}
```

If everything looks correct, do you have access to the Facebook app? If it's in development mode you need to be added as at least a tester. This can be verified here:
https://developers.facebook.com/apps/[app_id_here]/roles/

If it still doesn't work, you might try taking the app out of development mode to see if that works.

**Comment by calebduren** [comment]
I gave this a try today and am getting the same error. 

```
{"message":"Missing credentials in config","code":"CredentialsError","time":"2015-05-27T19:15:45.193Z","statusCode":403,"retryable":false,"retryDelay":30,"originalError":{"message":"Could not load credentials from ","code":"CredentialsError","time":"2015-05-27T19:15:45.193Z","statusCode":403,"retryable":false,"retryDelay":30,"originalError":{"message":"Not authorized to perform sts:AssumeRoleWithWebIdentity","code":"AccessDenied","time":"2015-05-27T19:15:45.193Z","statusCode":403,"retryable":false,"retryDelay":30}}}
```

**Comment by Peksa** [comment]
Interesting! Thanks for getting in touch. I think at this stage I'll try to follow my own instructions with a new domain and see if I can recreate the error.

**Comment by calebduren** [comment]
Thanks! I appreciate your work on this.

**Comment by Peksa** [comment]
Somewhat good news! I just set up a new domain (http://16.rs) following my own instructions, and I get the same error! :) I'll investigate and get back!

**Comment by Peksa** [comment]
Alright, I figured it out. The problem is that new Facebook apps are created using the Graph 2.0 API. One of the changes compared to 1.0 is that Facebook User IDs are generated per app. This seems to be to ensure that a Facebook app never receives the real user id from Facebook.

This means that you need to figure out the "app specific" user id of your Facebook account and then update your Trust Relationship for your Role in AWS IAM.

To figure out your app-specific ID, the easiest way is to see look at the request that fails when you try to login on your domain. Look at the request using for instance Chrome devtools, the request should look like this:

https://sts.amazonaws.com/?Action=AssumeRoleWithWebIdentity&ProviderId=graph.facebook.com&RoleArn=arn%3Aaws%3Aiam%3A%3A507606061091%3Arole%2F16.rs&RoleSessionName=web-identity&Version=2011-06-15&WebIdentityToken= `<Some very long access token>`

Extract the access token, and then visit this url:

https://graph.facebook.com/me?access_token=YOUR_TOKEN

This should give you something like: (note that it says app_scoped_user_id)

``` json
{
   "id": "10152943235213997",
   "first_name": "Niklas",
   "gender": "male",
   "last_name": "M\u00f6rnesten",
   "link": "https://www.facebook.com/app_scoped_user_id/10152943235213997/",
   "locale": "en_US",
   "name": "Niklas M\u00f6rnesten",
   "timezone": 2,
   "verified": true
}
```

Save this id, and then use it to update your Trust Relationship in your IAM Role. After updating the role, it should work!

Fingers crossed!

**Comment by calebduren** [comment]
Yes, this fixes the issue. Just to clarify for others: this new `id` is replacing the value for `graph.facebook.com:id`, not `graph.facebook.com:app_id`.  

Thanks, Peska!

**Comment by Peksa** [comment]
Great! Thanks for verifying. I'll update the README.md with new instructions.

**Comment by samiajia** [comment]
Hi guys, sorry for the late reply, just got back from honeymoon from Japan :) Anyways, will try the solution tonight. Thanks a million Peksa! Will keep you updated.

**Comment by samiajia** [comment]
It works! Thanks a million! You're the best!

**Comment by Peksa** [comment]
Excellent, thanks and congrats! :)
